LEVELS: list[dict] = [
    {
    "id": 1,
    "name": "First Drop",
    "hint": "Draw a ramp so the ball rolls into the green target.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 420,
    "ball": {
        "x": 140,
        "y": 90,
        "radius": 14,
    },
    "target": {
        "x": 660,
        "y": 520,
        "radius": 28,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 120,
            "y": 420,
            "width": 180,
            "height": 16,
        },
    ],
},
    {
    "id": 2,
    "name": "The Gap",
    "hint": "Bridge the gap between the two platforms.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 380,
    "ball": {
        "x": 110,
        "y": 80,
        "radius": 14,
    },
    "target": {
        "x": 690,
        "y": 500,
        "radius": 26,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 150,
            "y": 360,
            "width": 220,
            "height": 16,
        },
        {
            "type": "rect",
            "x": 650,
            "y": 360,
            "width": 220,
            "height": 16,
        },
    ],
},
    {
    "id": 3,
    "name": "Bounce Pad",
    "hint": "Use a steep slope to launch the ball toward the target.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 360,
    "ball": {
        "x": 120,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 700,
        "y": 540,
        "radius": 24,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 460,
            "width": 520,
            "height": 16,
            "angle": -0.18,
        },
        {
            "type": "rect",
            "x": 620,
            "y": 320,
            "width": 140,
            "height": 16,
        },
    ],
},
    {
    "id": 4,
    "name": "Pinball",
    "hint": "Guide the ball through the obstacles.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 340,
    "ball": {
        "x": 400,
        "y": 80,
        "radius": 14,
    },
    "target": {
        "x": 720,
        "y": 520,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 250,
            "y": 280,
            "width": 120,
            "height": 16,
            "angle": 0.5,
        },
        {
            "type": "rect",
            "x": 550,
            "y": 380,
            "width": 120,
            "height": 16,
            "angle": -0.45,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 480,
            "width": 80,
            "height": 80,
        },
    ],
},
    {
    "id": 5,
    "name": "Master Stroke",
    "hint": "Limited ink \u2014 every line counts.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 260,
    "ball": {
        "x": 90,
        "y": 100,
        "radius": 13,
    },
    "target": {
        "x": 710,
        "y": 510,
        "radius": 20,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 160,
            "y": 400,
            "width": 140,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 520,
            "y": 320,
            "width": 160,
            "height": 14,
            "angle": 0.35,
        },
        {
            "type": "rect",
            "x": 680,
            "y": 440,
            "width": 100,
            "height": 14,
            "angle": -0.25,
        },
    ],
},
    {
    "id": 6,
    "name": "Stairway",
    "hint": "Build steps that carry the ball upward and right.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 400,
    "ball": {
        "x": 100,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 680,
        "y": 480,
        "radius": 24,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 180,
            "y": 480,
            "width": 120,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 320,
            "y": 400,
            "width": 120,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 460,
            "y": 320,
            "width": 120,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 600,
            "y": 240,
            "width": 120,
            "height": 14,
        },
    ],
},
    {
    "id": 7,
    "name": "Funnel",
    "hint": "Guide the ball through the narrow opening.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 380,
    "ball": {
        "x": 400,
        "y": 60,
        "radius": 14,
    },
    "target": {
        "x": 400,
        "y": 530,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 280,
            "y": 350,
            "width": 16,
            "height": 180,
        },
        {
            "type": "rect",
            "x": 520,
            "y": 350,
            "width": 16,
            "height": 180,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 260,
            "width": 200,
            "height": 14,
        },
    ],
},
    {
    "id": 8,
    "name": "The Well",
    "hint": "Drop the ball into the pit from above.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 360,
    "ball": {
        "x": 400,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 400,
        "y": 500,
        "radius": 26,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 380,
            "width": 280,
            "height": 16,
        },
        {
            "type": "rect",
            "x": 320,
            "y": 300,
            "width": 16,
            "height": 120,
        },
        {
            "type": "rect",
            "x": 480,
            "y": 300,
            "width": 16,
            "height": 120,
        },
    ],
},
    {
    "id": 9,
    "name": "Split Path",
    "hint": "Choose the safer route around the center block.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 370,
    "ball": {
        "x": 120,
        "y": 80,
        "radius": 14,
    },
    "target": {
        "x": 700,
        "y": 500,
        "radius": 24,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 340,
            "width": 80,
            "height": 160,
        },
        {
            "type": "rect",
            "x": 200,
            "y": 420,
            "width": 160,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 600,
            "y": 420,
            "width": 160,
            "height": 14,
        },
    ],
},
    {
    "id": 10,
    "name": "Gate Crash",
    "hint": "Slip through the angled gates one at a time.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 350,
    "ball": {
        "x": 400,
        "y": 65,
        "radius": 14,
    },
    "target": {
        "x": 720,
        "y": 520,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 250,
            "y": 250,
            "width": 100,
            "height": 14,
            "angle": 0.55,
        },
        {
            "type": "rect",
            "x": 550,
            "y": 320,
            "width": 100,
            "height": 14,
            "angle": -0.55,
        },
        {
            "type": "rect",
            "x": 350,
            "y": 420,
            "width": 100,
            "height": 14,
            "angle": 0.4,
        },
    ],
},
    {
    "id": 11,
    "name": "Zigzag",
    "hint": "Hop across alternating ledges.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 390,
    "ball": {
        "x": 90,
        "y": 75,
        "radius": 14,
    },
    "target": {
        "x": 710,
        "y": 490,
        "radius": 24,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 160,
            "y": 380,
            "width": 180,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 300,
            "width": 180,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 640,
            "y": 220,
            "width": 180,
            "height": 14,
        },
    ],
},
    {
    "id": 12,
    "name": "Tower Drop",
    "hint": "Circle the tower and reach the far side.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 360,
    "ball": {
        "x": 150,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 680,
        "y": 510,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "circle",
            "x": 400,
            "y": 320,
            "radius": 55,
        },
        {
            "type": "rect",
            "x": 620,
            "y": 400,
            "width": 140,
            "height": 14,
        },
    ],
},
    {
    "id": 13,
    "name": "Canyon",
    "hint": "Cross the deep canyon with a sturdy bridge.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 400,
    "ball": {
        "x": 120,
        "y": 85,
        "radius": 14,
    },
    "target": {
        "x": 680,
        "y": 520,
        "radius": 26,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 400,
            "width": 16,
            "height": 200,
        },
        {
            "type": "rect",
            "x": 180,
            "y": 360,
            "width": 140,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 620,
            "y": 360,
            "width": 140,
            "height": 14,
        },
    ],
},
    {
    "id": 14,
    "name": "Bumper Field",
    "hint": "Bounce off the pegs toward the target.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 380,
    "ball": {
        "x": 400,
        "y": 60,
        "radius": 14,
    },
    "target": {
        "x": 700,
        "y": 530,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "circle",
            "x": 280,
            "y": 280,
            "radius": 22,
        },
        {
            "type": "circle",
            "x": 520,
            "y": 320,
            "radius": 22,
        },
        {
            "type": "circle",
            "x": 360,
            "y": 420,
            "radius": 22,
        },
        {
            "type": "circle",
            "x": 580,
            "y": 460,
            "radius": 22,
        },
    ],
},
    {
    "id": 15,
    "name": "Spiral Stairs",
    "hint": "Climb the spiral one step at a time.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 410,
    "ball": {
        "x": 100,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 700,
        "y": 470,
        "radius": 24,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 200,
            "y": 500,
            "width": 100,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 300,
            "y": 420,
            "width": 100,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 340,
            "width": 100,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 500,
            "y": 260,
            "width": 100,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 600,
            "y": 180,
            "width": 100,
            "height": 14,
        },
    ],
},
    {
    "id": 16,
    "name": "Dead End",
    "hint": "The direct path is blocked \u2014 go over the wall.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 340,
    "ball": {
        "x": 120,
        "y": 80,
        "radius": 14,
    },
    "target": {
        "x": 680,
        "y": 500,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 350,
            "y": 400,
            "width": 16,
            "height": 160,
        },
        {
            "type": "rect",
            "x": 550,
            "y": 400,
            "width": 16,
            "height": 160,
        },
        {
            "type": "rect",
            "x": 450,
            "y": 320,
            "width": 120,
            "height": 14,
        },
    ],
},
    {
    "id": 17,
    "name": "High Wire",
    "hint": "Reach the distant ledge without falling short.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 320,
    "ball": {
        "x": 100,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 720,
        "y": 450,
        "radius": 20,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 680,
            "y": 470,
            "width": 100,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 350,
            "width": 14,
            "height": 140,
        },
    ],
},
    {
    "id": 18,
    "name": "Catapult",
    "hint": "Build a launch ramp off the steep slope.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 350,
    "ball": {
        "x": 150,
        "y": 75,
        "radius": 14,
    },
    "target": {
        "x": 700,
        "y": 540,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 300,
            "y": 380,
            "width": 160,
            "height": 14,
            "angle": -0.65,
        },
        {
            "type": "rect",
            "x": 550,
            "y": 300,
            "width": 120,
            "height": 14,
        },
    ],
},
    {
    "id": 19,
    "name": "Maze Lite",
    "hint": "Navigate around the box obstacles.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 370,
    "ball": {
        "x": 80,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 720,
        "y": 510,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 250,
            "y": 300,
            "width": 140,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 450,
            "y": 380,
            "width": 140,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 350,
            "y": 460,
            "width": 14,
            "height": 100,
        },
        {
            "type": "rect",
            "x": 550,
            "y": 260,
            "width": 14,
            "height": 100,
        },
    ],
},
    {
    "id": 20,
    "name": "Plinko",
    "hint": "Let the ball cascade through the pegs.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 390,
    "ball": {
        "x": 400,
        "y": 55,
        "radius": 14,
    },
    "target": {
        "x": 400,
        "y": 530,
        "radius": 24,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "circle",
            "x": 320,
            "y": 200,
            "radius": 18,
        },
        {
            "type": "circle",
            "x": 480,
            "y": 200,
            "radius": 18,
        },
        {
            "type": "circle",
            "x": 360,
            "y": 300,
            "radius": 18,
        },
        {
            "type": "circle",
            "x": 440,
            "y": 300,
            "radius": 18,
        },
        {
            "type": "circle",
            "x": 400,
            "y": 400,
            "radius": 18,
        },
    ],
},
    {
    "id": 21,
    "name": "The Ledge",
    "hint": "Roll the ball onto the high ledge.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 360,
    "ball": {
        "x": 120,
        "y": 80,
        "radius": 14,
    },
    "target": {
        "x": 650,
        "y": 380,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 620,
            "y": 400,
            "width": 160,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 300,
            "y": 480,
            "width": 200,
            "height": 14,
            "angle": -0.2,
        },
    ],
},
    {
    "id": 22,
    "name": "Labyrinth",
    "hint": "Find the path through the walled corridor.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 330,
    "ball": {
        "x": 100,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 700,
        "y": 520,
        "radius": 20,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 300,
            "y": 250,
            "width": 14,
            "height": 160,
        },
        {
            "type": "rect",
            "x": 500,
            "y": 350,
            "width": 14,
            "height": 160,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 450,
            "width": 200,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 200,
            "y": 350,
            "width": 120,
            "height": 14,
        },
    ],
},
    {
    "id": 23,
    "name": "Double Gap",
    "hint": "Bridge two gaps in a row.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 380,
    "ball": {
        "x": 90,
        "y": 75,
        "radius": 14,
    },
    "target": {
        "x": 710,
        "y": 500,
        "radius": 24,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 200,
            "y": 380,
            "width": 160,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 380,
            "width": 16,
            "height": 120,
        },
        {
            "type": "rect",
            "x": 600,
            "y": 380,
            "width": 160,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 280,
            "width": 160,
            "height": 14,
        },
    ],
},
    {
    "id": 24,
    "name": "Island Hop",
    "hint": "Hop between tiny floating platforms.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 400,
    "ball": {
        "x": 100,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 700,
        "y": 480,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 220,
            "y": 420,
            "width": 80,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 380,
            "y": 350,
            "width": 80,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 540,
            "y": 280,
            "width": 80,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 680,
            "y": 420,
            "width": 80,
            "height": 14,
        },
    ],
},
    {
    "id": 25,
    "name": "The Slide",
    "hint": "Send the ball down the long ramp.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 360,
    "ball": {
        "x": 150,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 700,
        "y": 530,
        "radius": 24,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 350,
            "width": 500,
            "height": 16,
            "angle": -0.12,
        },
        {
            "type": "rect",
            "x": 600,
            "y": 450,
            "width": 120,
            "height": 14,
        },
    ],
},
    {
    "id": 26,
    "name": "Corkscrew",
    "hint": "Wind down through the offset platforms.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 380,
    "ball": {
        "x": 680,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 120,
        "y": 520,
        "radius": 24,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 600,
            "y": 200,
            "width": 120,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 480,
            "y": 300,
            "width": 120,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 360,
            "y": 400,
            "width": 120,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 240,
            "y": 480,
            "width": 120,
            "height": 14,
        },
    ],
},
    {
    "id": 27,
    "name": "Narrow Gate",
    "hint": "Thread the needle into the target alcove.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 310,
    "ball": {
        "x": 400,
        "y": 60,
        "radius": 14,
    },
    "target": {
        "x": 400,
        "y": 520,
        "radius": 20,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 340,
            "y": 380,
            "width": 14,
            "height": 120,
        },
        {
            "type": "rect",
            "x": 460,
            "y": 380,
            "width": 14,
            "height": 120,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 300,
            "width": 80,
            "height": 14,
        },
    ],
},
    {
    "id": 28,
    "name": "The Pillar",
    "hint": "Wrap around the central pillar.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 350,
    "ball": {
        "x": 400,
        "y": 65,
        "radius": 14,
    },
    "target": {
        "x": 700,
        "y": 520,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "circle",
            "x": 400,
            "y": 350,
            "radius": 45,
        },
        {
            "type": "rect",
            "x": 620,
            "y": 440,
            "width": 140,
            "height": 14,
            "angle": -0.15,
        },
    ],
},
    {
    "id": 29,
    "name": "Corner Pocket",
    "hint": "Sink the ball into the bottom-right pocket.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 340,
    "ball": {
        "x": 120,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 740,
        "y": 540,
        "radius": 20,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 650,
            "y": 450,
            "width": 14,
            "height": 160,
        },
        {
            "type": "rect",
            "x": 580,
            "y": 380,
            "width": 140,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 300,
            "y": 400,
            "width": 14,
            "height": 120,
        },
    ],
},
    {
    "id": 30,
    "name": "S-Curve",
    "hint": "Follow the S-curve path downward.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 370,
    "ball": {
        "x": 150,
        "y": 75,
        "radius": 14,
    },
    "target": {
        "x": 680,
        "y": 510,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 280,
            "y": 300,
            "width": 140,
            "height": 14,
            "angle": 0.35,
        },
        {
            "type": "rect",
            "x": 520,
            "y": 400,
            "width": 140,
            "height": 14,
            "angle": -0.35,
        },
        {
            "type": "rect",
            "x": 350,
            "y": 480,
            "width": 140,
            "height": 14,
            "angle": 0.25,
        },
    ],
},
    {
    "id": 31,
    "name": "Domino Run",
    "hint": "Set up a chain of angled domino ramps.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 360,
    "ball": {
        "x": 100,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 710,
        "y": 500,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 200,
            "y": 450,
            "width": 100,
            "height": 14,
            "angle": 0.3,
        },
        {
            "type": "rect",
            "x": 350,
            "y": 380,
            "width": 100,
            "height": 14,
            "angle": -0.25,
        },
        {
            "type": "rect",
            "x": 500,
            "y": 310,
            "width": 100,
            "height": 14,
            "angle": 0.3,
        },
        {
            "type": "rect",
            "x": 650,
            "y": 420,
            "width": 100,
            "height": 14,
            "angle": -0.2,
        },
    ],
},
    {
    "id": 32,
    "name": "The Vault",
    "hint": "Climb over the vault wall to reach the target.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 330,
    "ball": {
        "x": 120,
        "y": 80,
        "radius": 14,
    },
    "target": {
        "x": 680,
        "y": 480,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 450,
            "y": 400,
            "width": 16,
            "height": 180,
        },
        {
            "type": "rect",
            "x": 450,
            "y": 300,
            "width": 160,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 620,
            "y": 420,
            "width": 140,
            "height": 14,
        },
    ],
},
    {
    "id": 33,
    "name": "Seesaw",
    "hint": "Cross the tilted plank without sliding off.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 350,
    "ball": {
        "x": 200,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 680,
        "y": 500,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 420,
            "y": 380,
            "width": 220,
            "height": 14,
            "angle": 0.22,
        },
        {
            "type": "rect",
            "x": 620,
            "y": 460,
            "width": 120,
            "height": 14,
        },
    ],
},
    {
    "id": 34,
    "name": "Gauntlet",
    "hint": "Survive the obstacle gauntlet.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 400,
    "ball": {
        "x": 400,
        "y": 55,
        "radius": 14,
    },
    "target": {
        "x": 720,
        "y": 530,
        "radius": 20,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 250,
            "y": 220,
            "width": 80,
            "height": 14,
            "angle": 0.4,
        },
        {
            "type": "rect",
            "x": 550,
            "y": 280,
            "width": 80,
            "height": 14,
            "angle": -0.4,
        },
        {
            "type": "rect",
            "x": 350,
            "y": 360,
            "width": 80,
            "height": 14,
            "angle": 0.35,
        },
        {
            "type": "rect",
            "x": 500,
            "y": 420,
            "width": 80,
            "height": 14,
            "angle": -0.35,
        },
        {
            "type": "circle",
            "x": 400,
            "y": 480,
            "radius": 25,
        },
    ],
},
    {
    "id": 35,
    "name": "Long Shot",
    "hint": "A long journey with very little ink.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 240,
    "ball": {
        "x": 80,
        "y": 80,
        "radius": 13,
    },
    "target": {
        "x": 720,
        "y": 520,
        "radius": 20,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 200,
            "y": 420,
            "width": 140,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 500,
            "y": 340,
            "width": 160,
            "height": 14,
            "angle": 0.2,
        },
    ],
},
    {
    "id": 36,
    "name": "Hourglass",
    "hint": "Pass through the pinched middle.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 360,
    "ball": {
        "x": 400,
        "y": 60,
        "radius": 14,
    },
    "target": {
        "x": 400,
        "y": 530,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 250,
            "y": 250,
            "width": 140,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 550,
            "y": 250,
            "width": 140,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 300,
            "y": 400,
            "width": 14,
            "height": 120,
        },
        {
            "type": "rect",
            "x": 500,
            "y": 400,
            "width": 14,
            "height": 120,
        },
    ],
},
    {
    "id": 37,
    "name": "Roller Coaster",
    "hint": "Ride the series of steep ramps.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 380,
    "ball": {
        "x": 120,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 700,
        "y": 520,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 250,
            "y": 350,
            "width": 140,
            "height": 14,
            "angle": -0.4,
        },
        {
            "type": "rect",
            "x": 450,
            "y": 280,
            "width": 140,
            "height": 14,
            "angle": 0.35,
        },
        {
            "type": "rect",
            "x": 620,
            "y": 400,
            "width": 140,
            "height": 14,
            "angle": -0.3,
        },
    ],
},
    {
    "id": 38,
    "name": "The Trap",
    "hint": "Enter the trap through the only opening.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 340,
    "ball": {
        "x": 400,
        "y": 65,
        "radius": 14,
    },
    "target": {
        "x": 400,
        "y": 500,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 320,
            "y": 380,
            "width": 14,
            "height": 140,
        },
        {
            "type": "rect",
            "x": 480,
            "y": 380,
            "width": 14,
            "height": 140,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 320,
            "width": 140,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 440,
            "width": 80,
            "height": 14,
        },
    ],
},
    {
    "id": 39,
    "name": "Floating Isles",
    "hint": "Leap across widely spaced islands.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 410,
    "ball": {
        "x": 80,
        "y": 75,
        "radius": 14,
    },
    "target": {
        "x": 720,
        "y": 490,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 180,
            "y": 450,
            "width": 70,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 340,
            "y": 360,
            "width": 70,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 500,
            "y": 270,
            "width": 70,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 660,
            "y": 380,
            "width": 70,
            "height": 14,
        },
    ],
},
    {
    "id": 40,
    "name": "The Chute",
    "hint": "Drop the ball through the vertical chute.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 350,
    "ball": {
        "x": 400,
        "y": 55,
        "radius": 14,
    },
    "target": {
        "x": 400,
        "y": 520,
        "radius": 24,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 360,
            "y": 300,
            "width": 14,
            "height": 200,
        },
        {
            "type": "rect",
            "x": 440,
            "y": 300,
            "width": 14,
            "height": 200,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 220,
            "width": 60,
            "height": 14,
        },
    ],
},
    {
    "id": 41,
    "name": "Balance Beam",
    "hint": "Cross the thin balance beam.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 300,
    "ball": {
        "x": 150,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 680,
        "y": 480,
        "radius": 20,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 420,
            "y": 400,
            "width": 200,
            "height": 10,
        },
        {
            "type": "rect",
            "x": 620,
            "y": 460,
            "width": 100,
            "height": 14,
        },
    ],
},
    {
    "id": 42,
    "name": "Ricochet",
    "hint": "Bank shots off the circular bumpers.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 370,
    "ball": {
        "x": 100,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 710,
        "y": 510,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "circle",
            "x": 350,
            "y": 280,
            "radius": 30,
        },
        {
            "type": "circle",
            "x": 550,
            "y": 350,
            "radius": 30,
        },
        {
            "type": "rect",
            "x": 450,
            "y": 450,
            "width": 120,
            "height": 14,
            "angle": 0.15,
        },
    ],
},
    {
    "id": 43,
    "name": "Fortress",
    "hint": "Breach the fortress walls.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 330,
    "ball": {
        "x": 400,
        "y": 60,
        "radius": 14,
    },
    "target": {
        "x": 680,
        "y": 500,
        "radius": 20,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 500,
            "y": 380,
            "width": 14,
            "height": 160,
        },
        {
            "type": "rect",
            "x": 620,
            "y": 380,
            "width": 14,
            "height": 160,
        },
        {
            "type": "rect",
            "x": 560,
            "y": 300,
            "width": 120,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 680,
            "y": 440,
            "width": 100,
            "height": 14,
        },
    ],
},
    {
    "id": 44,
    "name": "Triple Bounce",
    "hint": "Bounce three times before the finish.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 360,
    "ball": {
        "x": 120,
        "y": 75,
        "radius": 14,
    },
    "target": {
        "x": 700,
        "y": 530,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 250,
            "y": 400,
            "width": 120,
            "height": 14,
            "angle": -0.45,
        },
        {
            "type": "rect",
            "x": 420,
            "y": 320,
            "width": 120,
            "height": 14,
            "angle": 0.4,
        },
        {
            "type": "rect",
            "x": 580,
            "y": 440,
            "width": 120,
            "height": 14,
            "angle": -0.35,
        },
    ],
},
    {
    "id": 45,
    "name": "The Needle",
    "hint": "Thread the needle with precision.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 260,
    "ball": {
        "x": 400,
        "y": 60,
        "radius": 14,
    },
    "target": {
        "x": 720,
        "y": 520,
        "radius": 18,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 350,
            "y": 350,
            "width": 14,
            "height": 140,
        },
        {
            "type": "rect",
            "x": 450,
            "y": 350,
            "width": 14,
            "height": 140,
        },
        {
            "type": "rect",
            "x": 550,
            "y": 420,
            "width": 120,
            "height": 14,
        },
    ],
},
    {
    "id": 46,
    "name": "Cascade",
    "hint": "Let the ball cascade down the terraces.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 390,
    "ball": {
        "x": 680,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 120,
        "y": 520,
        "radius": 24,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 600,
            "y": 180,
            "width": 130,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 480,
            "y": 280,
            "width": 130,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 360,
            "y": 380,
            "width": 130,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 240,
            "y": 480,
            "width": 130,
            "height": 14,
        },
    ],
},
    {
    "id": 47,
    "name": "The Arch",
    "hint": "Roll under the arch and into the target.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 350,
    "ball": {
        "x": 150,
        "y": 70,
        "radius": 14,
    },
    "target": {
        "x": 650,
        "y": 510,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 320,
            "width": 200,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 320,
            "y": 260,
            "width": 14,
            "height": 100,
        },
        {
            "type": "rect",
            "x": 480,
            "y": 260,
            "width": 14,
            "height": 100,
        },
    ],
},
    {
    "id": 48,
    "name": "Switchback",
    "hint": "Climb the switchback trail.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 370,
    "ball": {
        "x": 90,
        "y": 75,
        "radius": 14,
    },
    "target": {
        "x": 710,
        "y": 490,
        "radius": 22,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 200,
            "y": 480,
            "width": 140,
            "height": 14,
            "angle": 0.5,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 380,
            "width": 140,
            "height": 14,
            "angle": -0.5,
        },
        {
            "type": "rect",
            "x": 600,
            "y": 280,
            "width": 140,
            "height": 14,
            "angle": 0.45,
        },
    ],
},
    {
    "id": 49,
    "name": "Final Bridge",
    "hint": "One last long bridge to the tiny target.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 280,
    "ball": {
        "x": 100,
        "y": 80,
        "radius": 13,
    },
    "target": {
        "x": 720,
        "y": 510,
        "radius": 18,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "rect",
            "x": 200,
            "y": 400,
            "width": 160,
            "height": 14,
        },
        {
            "type": "rect",
            "x": 500,
            "y": 320,
            "width": 14,
            "height": 140,
        },
        {
            "type": "rect",
            "x": 650,
            "y": 450,
            "width": 100,
            "height": 14,
        },
    ],
},
    {
    "id": 50,
    "name": "Gravity Master",
    "hint": "The ultimate test \u2014 prove you master gravity.",
    "world_width": 800,
    "world_height": 600,
    "max_ink": 250,
    "ball": {
        "x": 400,
        "y": 55,
        "radius": 13,
    },
    "target": {
        "x": 400,
        "y": 520,
        "radius": 18,
    },
    "static_bodies": [
        {
            "type": "rect",
            "x": 400,
            "y": 580,
            "width": 760,
            "height": 24,
        },
        {
            "type": "circle",
            "x": 280,
            "y": 250,
            "radius": 28,
        },
        {
            "type": "circle",
            "x": 520,
            "y": 250,
            "radius": 28,
        },
        {
            "type": "rect",
            "x": 350,
            "y": 380,
            "width": 14,
            "height": 120,
        },
        {
            "type": "rect",
            "x": 450,
            "y": 380,
            "width": 14,
            "height": 120,
        },
        {
            "type": "rect",
            "x": 400,
            "y": 300,
            "width": 100,
            "height": 14,
            "angle": 0.2,
        },
        {
            "type": "rect",
            "x": 250,
            "y": 450,
            "width": 100,
            "height": 14,
            "angle": -0.3,
        },
        {
            "type": "rect",
            "x": 550,
            "y": 450,
            "width": 100,
            "height": 14,
            "angle": 0.3,
        },
    ],
},
]
